<a href="https://colab.research.google.com/github/Davidtar12/keyrus-csv-audit/blob/master/prueba_keyrus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/lakeside_orders_sample.csv")

In [ ]:
df.head()

,order_id,order_dt,ship_dt,cust_id,cust_name,cust_email,cust_seg_cd,prod_sku,prod_cat,qty,...,line_total,currency,chnl,pmt_method,ord_status,ship_country,ship_region,ship_postal,csat_score,svc_notes
0,ORD-50276,"Mar 24, 2024",2024-03-22,CUST-10164,Ines Laurent,INES.LAURENT@EXAMPLE.COM,A2,SKU-1751,HOME & KITCHEN,4,...,186.40,cad,WEB,Gift Card,Returned,canada,ontario,V9A 3E2,4.0,"Order placed in store but shipped to home, tra..."
1,ORD-50647,"Jul 07, 2024",2024-07-09,CUST-10311,Hugo Novak,hugo.novak@example.com,C3,SKU-1216,ELECTRONICS,250,...,14535.39,USD,store,debit_card,pending,us,TX,72755,NaN,"Customer says price was lower yesterday, asked..."
2,ORD-50062,30-09-2024,2024-10-01,CUST-10105,Leila Haddad,lhaddad@testmail.org,C1,SKU-1887,Grocery,2,...,229.50,USD,WEB,debit_card,COMPLETED,U.S.,california,52217,NaN,Asked to split delivery across two addresses -...
3,ORD-50660,2025-02-09,2025-02-12,CUST-10106,Aisha Johnson,aisha.johnson@example.com,B1,SKU-1582,Pet Supplies,1,...,24.78,USD,marketplace,credit_card,COMPLETED,United States,NJ,95697,2.0,Third return this quarter from this customer.
4,ORD-50661,2025-01-10,2025-01-13,CUST-10146,Aisha Johnson,aisha95@mailinator.com,NaN,SKU-1769,Home & Kitchen,1,...,9.59,USD,WEB,debit_card,shipped,US,TX,27495,5.0,Duplicate order - customer clicked submit twic...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1182 entries, 0 to 1181
Data columns (total 22 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      1182 non-null   object
 1   order_dt      1182 non-null   object
 2   ship_dt       1118 non-null   object
 3   cust_id       1182 non-null   object
 4   cust_name     1129 non-null   object
 5   cust_email    1103 non-null   object
 6   cust_seg_cd   1043 non-null   object
 7   prod_sku      1182 non-null   object
 8   prod_cat      1137 non-null   object
 9   qty           1182 non-null   int64
 10  unit_price    1154 non-null   float64
 11  disc_pct      1053 non-null   object
 12  line_total    1154 non-null   float64
 13  currency      1096 non-null   object
 14  chnl          1182 non-null   object
 15  pmt_method    1069 non-null   object
 16  ord_status    1182 non-null   object
 17  ship_country  1182 non-null   object
 18  ship_region   1182 non-null   object
 19  ship_postal   1182 non-null   object
 20  csat_score    1021 non-null   float64
 21  svc_notes     1127 non-null   object
dtypes: float64(3), int64(1), object(18)
memory usage: 203.3+ KB

In [ ]:
df.describe()

               qty   unit_price    line_total   csat_score
count  1182.000000  1154.000000   1154.000000  1021.000000
mean      2.717428   148.669315    368.376118     4.197845
std      12.609407   256.068611   1045.099044     1.683843
min      -1.000000     8.990000   -809.120000     1.000000
25%       1.000000    21.987500     32.140000     3.000000
50%       2.000000    48.295000     86.575000     4.000000
75%       3.000000   115.095000    239.405000     5.000000
max     250.000000   986.790000  15910.000000    10.000000

In [ ]:
disc_clean = pd.to_numeric(
    df["disc_pct"].str.replace("%", "", regex=False), errors="coerce"
) / 100

disc_clean.isnull().sum()

df.loc[disc_clean.isna(), "disc_pct"].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
df[df.duplicated(keep=False)].head()

,order_id,order_dt,ship_dt,cust_id,cust_name,cust_email,cust_seg_cd,prod_sku,prod_cat,qty,...,line_total,currency,chnl,pmt_method,ord_status,ship_country,ship_region,ship_postal,csat_score,svc_notes
5,ORD-51001,2025-02-04,2025-02-05,CUST-10307,Sofia Johnson,sjohnson@testmail.org,C3,SKU-1090,Apparel,4,...,480.08,CAD,store,apple_pay,completed,CAN,ON,M1H 7C7,5.0,"Order placed in store but shipped to home, tra..."
15,ORD-50808,1741735020,2025-03-14,CUST-10272,Hugo Alvarez,HUGO.ALVAREZ@EXAMPLE.COM,B1,SKU-1859,Beauty & Personal Care,1,...,49.10,CAD,in store,PayPal,Pending,Canada,QC,P5A 7B4,5.0,"Customer says price was lower yesterday, asked..."
33,ORD-50884,04/16/2024,2024-04-18,CUST-10157,Felix Nasser,FELIX.NASSER@EXAMPLE.COM,B1,SKU-1673,Apparel,2,...,255.48,USD,mobile_app,PayPal,shipped,U.S.,new york,66681,5.0,Payment declined twice before going through.
116,ORD-51001,2025-02-04,2025-02-05,CUST-10307,Sofia Johnson,sjohnson@testmail.org,C3,SKU-1090,Apparel,4,...,480.08,CAD,store,apple_pay,completed,CAN,ON,M1H 7C7,5.0,"Order placed in store but shipped to home, tra..."
153,ORD-50471,2024-01-01,2024-01-02,CUST-10308,NaN,ethan.nasser@example.com,B1,SKU-1099,grocery,5,...,450.40,USD,mobile_app,PayPal,Pending,USA,CA,58866,2.0,Product missing accessory listed on the page.

In [ ]:
df.duplicated().sum()

np.int64(20)

In [ ]:
df["order_dt"].value_counts()
patrones = df["order_dt"].str.replace(r"\d", "9", regex=True)
patrones.value_counts()

order_dt
9999-99-99             530
99/99/9999             235
9999-99-99 99:99:99    193
99-99-9999              96
9999999999              35
Feb 99, 9999            14
Jan 99, 9999            14
Mar 99, 9999            13
Apr 99, 9999            12
Jun 99, 9999             8
Oct 99, 9999             8
Jul 99, 9999             6
May 99, 9999             6
Aug 99, 9999             5
Nov 99, 9999             3
Sep 99, 9999             2
Dec 99, 9999             2
Name: count, dtype: int64

In [ ]:
patrones2 = df["ship_dt"].str.replace(r"\d", "9", regex=True)
patrones2.value_counts()

ship_dt
9999-99-99    1118
Name: count, dtype: int64

In [ ]:
order_dt_parse = pd.to_datetime(df["order_dt"], errors="coerce", format="mixed")
order_dt_parse.isna().sum()

np.int64(35)

In [ ]:
(df["ship_dt"] < order_dt_parse).sum()

np.int64(39)

In [ ]:
 df["ord_status"].value_counts()

ord_status
Returned     123
Pending      109
cancelled    105
returned     102
pending      100
Shipped       99
completed     97
shipped       97
Completed     93
COMPLETED     88
canceled      87
Cancelled     82
Name: count, dtype: int64

In [ ]:
df["ord_status"].str.lower().value_counts()

ord_status
completed    278
returned     225
pending      209
shipped      196
cancelled    187
canceled      87
Name: count, dtype: int64

In [ ]:
df["line_total_esperado"] = df["qty"] * df["unit_price"] * (1 - disc_clean)

(df["line_total_esperado"] - df["line_total"]).abs().round(2).gt(0.01).sum()

np.int64(559)

In [ ]:
df["order_id"].str.extract(r"^([A-Z]+)-")[0].value_counts()

0
ORD    1182
Name: count, dtype: int64

In [ ]:
df["cust_id"].str.extract(r"^([A-Z]+)-")[0].value_counts()

0
CUST    1182
Name: count, dtype: int64

In [ ]:
df["prod_sku"].str.extract(r"^([A-Z]+)-")[0].value_counts()

0
SKU    1182
Name: count, dtype: int64

In [ ]:
df["ship_country"].value_counts()

ship_country
US               185
U.S.             182
USA              169
United States    168
us               157
CAN               92
CA                85
canada            77
Canada            67
Name: count, dtype: int64

In [ ]:
df[df["cust_name"].str.lower() == "aisha johnson"]

,order_id,order_dt,ship_dt,cust_id,cust_name,cust_email,cust_seg_cd,prod_sku,prod_cat,qty,...,currency,chnl,pmt_method,ord_status,ship_country,ship_region,ship_postal,csat_score,svc_notes,line_total_esperado
3,ORD-50660,2025-02-09,2025-02-12,CUST-10106,Aisha Johnson,aisha.johnson@example.com,B1,SKU-1582,Pet Supplies,1,...,USD,marketplace,credit_card,COMPLETED,United States,NJ,95697,2.0,Third return this quarter from this customer.,NaN
4,ORD-50661,2025-01-10,2025-01-13,CUST-10146,Aisha Johnson,aisha95@mailinator.com,NaN,SKU-1769,Home & Kitchen,1,...,USD,WEB,debit_card,shipped,US,TX,27495,5.0,Duplicate order - customer clicked submit twic...,7.672000
63,ORD-50097,02-04-2024,2024-04-03,CUST-10106,Aisha Johnson,aisha.johnson@example.com,C1,SKU-1270,PET SUPPLIES,1,...,CAD,WEB,credit_card,Shipped,CA,Quebec,M6E 2A1,1.0,Duplicate order - customer clicked submit twic...,9.020000
365,ORD-50908,"Aug 10, 2024",2024-08-15,CUST-10106,Aisha Johnson,NaN,C1,SKU-1806,Beauty,1,...,USD,In-Store,PayPal,shipped,US,TX,38627,1.0,"Requested gift wrap, was not applied. Customer...",119.470000
510,ORD-50136,2024-09-16,2024-09-18,CUST-10106,Aisha Johnson,aisha.johnson@example.com,B2,SKU-1648,Beauty & Personal Care,2,...,CAD,Mobile App,apple_pay,Completed,CA,B.C.,N4A 1G8,5.0,Duplicate order - customer clicked submit twic...,NaN
732,ORD-51135,07/28/2024,2024-07-31,CUST-10146,Aisha Johnson,aisha95@mailinator.com,C3,SKU-1232,electronics,2,...,USD,Mobile App,apple_pay,canceled,United States,IL,31578,5.0,"Asked about warranty length, unclear on produc...",463.771000
791,ORD-51134,2024-05-19,2024-05-22,CUST-10106,Aisha Johnson,aisha.johnson@example.com,A2,SKU-1263,home & kitchen,3,...,USD,web,NaN,Completed,US,MA,11995,5.0,Wants to know if this is compatible with the 2...,172.881000
843,ORD-50670,2025-02-15,2025-02-18,CUST-10146,Aisha Johnson,aisha95@mailinator.com,C1,SKU-1680,Home & Kitchen,1,...,cad,store,PayPal,Completed,Canada,NS,M5G 9A9,4.0,"Bulk order for office, asked about corporate a...",56.525085
856,ORD-51070,"Feb 02, 2025",2025-02-05,CUST-10106,Aisha Johnson,aisha.johnson@example.com,NaN,SKU-1756,Groceries,10,...,USD,mobile_app,CC,completed,United States,Fl,76298,NaN,Third return this quarter from this customer.,1183.022800
1016,ORD-51111,2024-08-10,2024-08-19,CUST-10146,Aisha Johnson,aisha95@mailinator.com,NaN,SKU-1962,BEAUTY,1,...,CAD,mobile_app,NaN,Pending,canada,ON,L6H 7H8,3.0,"Address correction after dispatch, carrier red...",926.490000
1131,ORD-50745,2025-03-12 04:00:00,2025-03-13,CUST-10106,Aisha Johnson,aisha.johnson@example.com,B2,SKU-1125,outdoor,3,...,USD,Mobile App,Debit,Completed,CAN,ontario,L1E 6J7,4.0,"Asked about warranty length, unclear on produc...",64.210500

In [ ]:
df_raw = pd.read_csv("/content/drive/MyDrive/lakeside_orders_sample.csv", keep_default_na=False)
df_raw["csat_score"].value_counts(dropna=False)

csat_score
5      347
4      336
3      180
       140
2       68
10      49
1       41
n/a     21
Name: count, dtype: int64